# Use an official Golang runtime as the base image
FROM golang:1.16-alpine

# Set the working directory inside the container
WORKDIR /go/src/app

# Copy the entire API server code to the container
COPY . .

# Build the API server executable
RUN go build -o api-server ./api

# Expose the port on which the server will listen
EXPOSE 8080

# Set the entry point to run the API server when the container starts
CMD ["./api-server"]
